<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<EnableWindowsTargeting>True</EnableWindowsTargeting>
	</PropertyGroup>

	<PropertyGroup>
		<Authors>$(CompanyName)</Authors>
		<Company>$(CompanyName)</Company>
		<Copyright>$(CompanyName)</Copyright>
		<Description>Provides authentication and token management for Azure Active Directory using MSAL, supporting secure token caching and integration with Azure SDK clients.</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IsPublishable>True</IsPublishable>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<PackageIcon>Logo.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://www.scotec-software.com</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<RepositoryUrl>https://github.com/scotec-Software-Solutions-AB/scotec_ssc</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<SignAssembly>False</SignAssembly>
		<Title>Scotec.Identity.AzureActiveDirectory</Title>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.51.1" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.82.1" />
		<PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.82.1" />
		<PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.82.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="" />
		<None Include="..\Logo.png" Pack="true" PackagePath="" />
		<Content Include="..\..\..\license.txt" Link="license.txt" Pack="true" PackagePath="license.txt" />
	</ItemGroup>

</Project>